In [1]:
%load_ext autoreload
%reload_ext autoreload
%autoreload 2

In [2]:
import os
import sys
root_dir = os.path.join(os.getcwd(), '..')
sys.path.append(root_dir)

In [7]:
import numpy as np
import png
from src.hello_world import HelloWorld as HW
from src.data_loader import DataLoader as DL

In [37]:
dl = DL()
image_data = dl.load_data_from_file(dl.PIZZA, 500)[dl.DRAWING]
data_tupels = dl.drawing_array_to_tupels(image_data)
print(data_tupels)
image = np.full((dl.width, dl.height), 1)

for t in data_tupels:
    image[t[0], t[1]] = 0
    
print(image)
print(len(image), len(image[0]))

image = [[int(c) for c in row] for row in image]
print(len(image), len(image[0]))

w = png.Writer(len(image[0]), len(image), greyscale=True, bitdepth=1)
f = open('test.png', 'wb')
w.write(f, image)
f.close()

[(229, 40), (221, 26), (208, 14), (189, 4), (174, 0), (135, 2), (93, 16), (73, 27), (39, 53), (27, 69), (9, 103), (5, 132), (9, 143), (20, 154), (36, 163), (55, 169), (101, 171), (150, 162), (211, 140), (238, 118), (248, 102), (255, 76), (253, 63), (246, 52), (225, 31), (193, 9), (183, 5), (158, 4), (143, 9), (136, 15), (124, 62), (95, 143), (210, 24), (86, 123), (42, 146), (45, 49), (180, 123), (201, 130), (212, 125), (244, 62), (195, 72), (4, 96), (0, 102), (105, 81), (103, 119), (91, 168), (58, 99), (49, 105), (46, 114), (55, 116), (65, 112), (67, 106), (60, 101), (109, 78), (104, 67), (89, 70), (80, 83), (82, 91), (89, 90), (100, 82), (103, 72), (100, 71), (142, 48), (136, 49), (130, 63), (131, 65), (136, 65), (150, 59), (151, 56), (143, 52), (143, 54)]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
256 256
256 256
