In [5]:
# Setup
%load_ext autoreload
%reload_ext autoreload
%autoreload 2

import os
import sys
root_dir = os.path.join(os.getcwd(), '..')
sys.path.append(root_dir)

import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

from src.data_loader import DataLoader as DL
from src.coach import train_in_batches

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
dl = DL()
data, labels = dl.load_data_batches(batch_size=10)
data_1d = np.array([dl.one_dimensional_array_from_matrix(mat) for mat in data])
X_train, X_test, y_train, y_test = train_test_split(data_1d, labels, test_size=0.3, shuffle=True)
print(X_train, X_test, y_train, y_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [0, 1, 2, 2, 2, 0, 0, 1, 2, 1, 0, 0, 2, 2, 2, 0, 1, 1, 1, 2, 1] [0, 0, 1, 0, 2, 2, 0, 1, 1]


In [3]:
# Split training data into more batches
no_of_batches = 300
X_train_batches = np.split(np.array(X_train), no_of_batches)
Y_train_batches = np.split(np.array(y_train), no_of_batches)

In [4]:
# hidden_layer_sizes=(128, 128, 64)
clf = MLPClassifier(hidden_layer_sizes=(128,))
clf.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(128,))

In [5]:
clf = MLPClassifier(hidden_layer_sizes=(128,))
clf.fit(X_train_batches[0], Y_train_batches[0])

MLPClassifier(hidden_layer_sizes=(128,))

In [6]:
clf.score(X_test, y_test)

0.39666666666666667

In [7]:
clf_batches = MLPClassifier(hidden_layer_sizes=(128,))
for i in range(len(X_train_batches)):
    clf_batches.partial_fit(X_train_batches[i], Y_train_batches[i], [0,1,2])

In [8]:
clf_batches.score(X_test, y_test)

0.8011111111111111

In [14]:
c = MLPClassifier()
c = train_in_batches(25_000, c)

(1500, 65536) (1500,)
0.934
